# Generated by Django 5.0.6 on 2025-09-30 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente', models.CharField(max_length=200)),
                ('fecha_utc', models.DateTimeField()),
                ('duracion_min', models.PositiveIntegerField(default=30)),
                ('calendar_id', models.CharField(max_length=100)),
                ('contact_id', models.CharField(blank=True, max_length=100, null=True)),
                ('synced', models.BooleanField(default=False)),
                ('ghl_appointment_id', models.CharField(blank=True, max_length=120, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
