name: Run Django Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set environment variables
        run: |
          echo "DEBUG=False" >> .env
          echo "SECRET_KEY=dummy-key-for-ci" >> .env
          echo "GHL_BASE_URL=https://services.leadconnectorhq.com" >> .env
          echo "GHL_PRIVATE_TOKEN=dummy-token" >> .env
          echo "GHL_LOCATION_ID=dummy-location" >> .env
          echo "GHL_CALENDAR_ID=dummy-calendar" >> .env

      - name: Run Django migrations
        run: |
          python manage.py migrate

      - name: Run Pytest
        run: |
          pytest -v
