name: Run Django Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create .env for tests
        run: |
          echo "DEBUG=False" >> .env
          echo "SECRET_KEY=test-key" >> .env
          echo "GHL_BASE_URL=https://services.leadconnectorhq.com" >> .env
          echo "GHL_PRIVATE_TOKEN=test-token" >> .env
          echo "GHL_LOCATION_ID=test-location" >> .env
          echo "GHL_CALENDAR_ID=test-calendar" >> .env

      - name: Run migrations
        run: python manage.py migrate

      - name: Run tests
        run: pytest -v
